### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by omarsawalhah** [oracle/create-database-app#14]
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/username/Developer/oracle/create-database-app/my-todo/.git/
Application generated successfuly. Run the following command:

cd /Users/username/Developer/oracle/create-database-app/my-todo
npm notice
npm notice New patch version of npm available! 10.8.1 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice To update run: npm install -g npm@10.8.2
npm notice
 > cd /Users/username/Developer/oracle/create-database-app/my-todo
 >  npm notice
Unknown command: "notice"

**Comment by mig8447** [comment]
Hello @omarsawalhah , 

Question: Do you have any special settings in your node configuration?

These messages starting with `hint:` `npm notice` seem to appear when npm output is verbose, In reality, `npm notice` is not a command that should be run but just a debug string printed by NPM.

The command that you should be executing is the `cd` command. After that, you can start the server using `npm run dev`. We'll make sure this is explicit in the output for next release.

**Comment by omarsawalhah** [comment]
no special settings, I used 
`nom run dev`
That worked.
